version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.2
    steps:
      - checkout
      - run:
          name: Release
          command: |
            npm i
            npx semantic-release
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
