brew 'zsh'

cask 'google-chrome'

cask '1password'
cask 'dropbox'
cask 'harvest'
cask 'slack'
cask 'fantastical'
cask 'notion'

cask 'rectangle'
cask 'appcleaner'

cask 'spotify'
cask 'vlc'
cask 'handbrake'

cask 'loom'
